In [1]:
import torch

In [2]:
### 自动微分

In [67]:
# 自动求导
# 在要求导的变量定义中加上requires_grad=True 表示要追踪这个变量的导数
x = torch.ones(2,2, requires_grad=True)
y = 2 * x+2

In [27]:
x.requires_grad
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [30]:
x2 = torch.ones(2,2)

In [33]:
# 默认不求导
x2.requires_grad


False

In [68]:
y.grad_fn

In [40]:
# 导数必须由标量输出创建，意思就是你要求的最后结果，必须是一个数，不能是一个向量
# y.backward()    # 报错

In [69]:
z = y.mean()
# 只有执行完backward之后，所有requires_grad=True的变量的导数都会被自动求出
# retain_graph=True，z变量进行backwar后会被自动释放，如果后续还需要多次backward，必须加上retain_graph=True
z.backward(retain_graph=True)

In [62]:
x.grad

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [70]:
z = y * y * 3
out = z.mean()
out

tensor(48., grad_fn=<MeanBackward0>)

In [71]:
out.backward()

In [73]:
# 求非叶子节点的tensor的导数，必须使用retain_grad,不然会报警
y.retain_grad

<function Tensor.retain_grad>

In [75]:
x.requires_grad

True

In [81]:
# 如果不需要求导，可以把代码包在torch.no_grad（）中,内部会禁止梯度计算
with torch.no_grad():
    # x是外部创建的，设置了可以求导，所以内部不影响，也可以求导
    print(x.requires_grad)
    print((x ** 2).requires_grad)

True
False


In [88]:
y = x ** 2
y.requires_grad

True

In [89]:
y = x.detach()
y.detach()

tensor([[1., 1.],
        [1., 1.]])

In [83]:
y.requires_grad

False

In [90]:
# 除了在定义变量的时候指定requires_grad=True，也可以使用requires_grad_()方法修改变量可导
a = torch.ones(2,3)
a = a * 2 + 3
a.requires_grad

False

In [91]:
a.requires_grad_()
a.requires_grad

True